// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0lSed-ntDdo1LKp9jV8ZCir3ahG569hA',
    appId: '1:846970418197:web:df885c4e529ac9f26cca1c',
    messagingSenderId: '846970418197',
    projectId: 'musicapp-76f80',
    authDomain: 'musicapp-76f80.firebaseapp.com',
    storageBucket: 'musicapp-76f80.appspot.com',
    measurementId: 'G-PPZNVEBVC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPoaKjD_KEo9A3qAzv6_faEbz3idcuK-M',
    appId: '1:846970418197:android:40f40d048c2cfdbb6cca1c',
    messagingSenderId: '846970418197',
    projectId: 'musicapp-76f80',
    storageBucket: 'musicapp-76f80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUCDvvV12N6CitFvnBw08aBlRpjjqnrM',
    appId: '1:846970418197:ios:2f3b45c59d3cfd6e6cca1c',
    messagingSenderId: '846970418197',
    projectId: 'musicapp-76f80',
    storageBucket: 'musicapp-76f80.appspot.com',
    iosBundleId: 'com.example.musix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIUCDvvV12N6CitFvnBw08aBlRpjjqnrM',
    appId: '1:846970418197:ios:2f3b45c59d3cfd6e6cca1c',
    messagingSenderId: '846970418197',
    projectId: 'musicapp-76f80',
    storageBucket: 'musicapp-76f80.appspot.com',
    iosBundleId: 'com.example.musix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0lSed-ntDdo1LKp9jV8ZCir3ahG569hA',
    appId: '1:846970418197:web:44117f5361a0458d6cca1c',
    messagingSenderId: '846970418197',
    projectId: 'musicapp-76f80',
    authDomain: 'musicapp-76f80.firebaseapp.com',
    storageBucket: 'musicapp-76f80.appspot.com',
    measurementId: 'G-P9WV5DHSMF',
  );
}
